name: angular_dart_ui_bootstrap
version: 0.0.1
description: >
  If you love Twitter Bootstrap and angularjs you can't avoid loving angular-ui (http://angular-ui.github.io/).
  This package is a porting of angular-ui bootstrap to dart. It contains a set of native Angular.dart components based on 
  Bootstrap's 3.x CSS. No dependency on Bootstrap's JavaScript is required.
author: Francesco Cina <ufoscout@google.com>
homepage: http://angular-dart-ui.github.io/
dependencies:
  angular: 0.9.4
dev_dependencies:
  unittest: any
  browser: any
  js: any
