name: angular_dart_ui_bootstrap
author: Francesco Cina <ufoscout@google.com>
version: 0.3.0
homepage: http://angular-dart-ui.github.io/
description: Port of angular-ui bootstrap (http://angular-ui.github.io/) to dart. It contains a set of native Angular.dart components based on  Bootstrap's 3.x CSS. No dependency on Bootstrap's JavaScript or Angular-ui is required.
dependencies:
  angular: 0.11.0
dev_dependencies:
  browser: any
  js: any
  web_components: ">=0.3.3 <0.4.0"
  unittest: '>=0.9.3 <0.10.0'
transformers:
- angular  
  